-- 한 줄 주석
/* 범위 주석 */

-- SQL 한 줄 실행 : ctrl + enter

/* SYS 관리자 계정으로 수행하는 SQL */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER KH_LSJ IDENTIFIED BY KH1234;

GRANT RESOURCE, CONNECT TO KH_LSJ;

ALTER USER KH_LSJ DEFAULT TABLESPACE SYSTEM QUOTA 20M ON USERS;