CREATE TABLE TODO_LIST(
	LIST_NO VARCHAR2 (20),
	LIST_TITLE VARCHAR2(20) NOT NULL,
	LIST_CHECK VARCHAR2(30BYTE), 
	LIST_COMPLETE VARCHAR2(20),
	ENROLL_DATE DATE
);

DROP TABLE TODO_LIST;

SELECT LIST_NO "번호", LIST_TITLE "할 일 제목", LIST_CHECK "완료 여부", lIST_COMPLETE, ENROLL_DATE "등록 날짜"
FROM TODO_LIST;

SELECT * FROM TODO_LIST;