CREATE TABLE TODO_LIST(
	LIST_NO NUMBER,
	LIST_TITLE VARCHAR2(200),
	LIST_CHECK VARCHAR2(4000), 
	LIST_COMPLETE NUMBER DEFAULT 0,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

SELECT LIST_NO, 
			 LIST_TITLE,
			 LIST_CHECK,
			 TO_CHAR(ENROLL_DATE, 'YYYY-MM-DD HH24:MI:SS') ENROLL_DATE
FROM TODO_LIST
WHERE LIST_NO > 0
ORDER BY LIST_NO ASC;

DROP TABLE TODO_LIST;

SELECT LIST_NO "번호", LIST_TITLE "할 일 제목", LIST_CHECK "완료 여부", lIST_COMPLETE, ENROLL_DATE "등록 날짜"
FROM TODO_LIST;

SELECT * FROM TODO_LIST;

-------------------------------------------


-- 제약 조건 추가
ALTER TABLE TODO_LIST
ADD CONSTRAINT TODO_LIST_PK PRIMARY KEY(LIST_NO);

ALTER TABLE TODO_LIST
MODIFY LIST_TITLE VARCHAR2(200) CONSTRAINT LIST_TITLE_NN NOT NULL;

ALTER TABLE TODO_LIST
MODIFY LIST_CHECK VARCHAR2(4000) CONSTRAINT LIST_CHECK_NN NOT NULL;

ALTER TABLE TODO_LIST
ADD CONSTRAINT LIST_COMPLETE_CHECK 
CHECK(LIST_COMPLETE IN (0, 1) );

COMMENT ON COLUMN TODO_LIST.LIST_NO IS '할 일 번호';
COMMENT ON COLUMN TODO_LIST.LIST_TITLE IS '할 일 제목';
COMMENT ON COLUMN TODO_LIST.LIST_CHECK IS '할 일 내용';
COMMENT ON COLUMN TODO_LIST.LIST_COMPLETE IS '할 일 완료 여부(0:X, 1:O)';
COMMENT ON COLUMN TODO_LIST.ENROLL_DATE IS '할 일 등록일';

-- 시퀀스 생성
CREATE SEQUENCE SEQ_LIST_NO NOCACHE;

-- 샘플 데이터
INSERT INTO TODO_LIST
VALUES(SEQ_LIST_NO.NEXTVAL, '테스트1', '테스트1 입니다.', DEFAULT, DEFAULT);

INSERT INTO TODO_LIST
VALUES(SEQ_LIST_NO.NEXTVAL, '테스트2', '테스트2 입니다.', DEFAULT, DEFAULT);

INSERT INTO TODO_LIST
VALUES(SEQ_LIST_NO.NEXTVAL, '테스트3', '테스트3 입니다.', DEFAULT, DEFAULT);


INSERT INTO TODO_LIST
VALUES(SEQ_LIST_NO.NEXTVAL, '테스트4', '테스트4 입니다.', DEFAULT, DEFAULT);

COMMIT;



-- 할일 목록 조회
SELECT 
	LIST_NO, 
	LIST_TITLE, 
	LIST_COMPLETE, 
	TO_CHAR(ENROLL_DATE, 'YYYY-MM-DD HH24:MI:SS') ENROLL_DATE
FROM TODO_LIST
WHERE LIST_NO > 0 -- INDEX가 설정된 PK 컬럼을 이용하면 조회 속도가 증가함
ORDER BY LIST_NO ASC;


-- 완료된 할 일 개수 조회
SELECT COUNT(*) 
FROM TODO_LIST
WHERE LIST_NO > 0
AND LIST_COMPLETE = 1;

-- 할 일 상세 조회
SELECT 
	LIST_NO, 
	LIST_TITLE, 
	LIST_CHECK,
	LIST_COMPLETE, 
	TO_CHAR(ENROLL_DATE, 'YYYY-MM-DD HH24:MI:SS') ENROLL_DATE
FROM TODO_LIST
WHERE LIST_NO = 1;


-- 할 일 완료 여부 변경(0<->1 변경)
UPDATE TODO_LIST
SET
	LIST_COMPLETE = 
		DECODE(LIST_COMPLETE, 0, 1, 0)
WHERE 
	LIST_NO = 1;

SELECT * FROM TODO_LIST;
COMMIT;



-- 할 일 수정
UPDATE TODO_LIST
SET
	LIST_TITLE = 'AAA',
	LIST_CHECK = 'BBB'
WHERE 
	LIST_NO = 1;


SELECT * FROM TODO_LIST;
COMMIT;

-------------------------------------------------------------------
UPDATE TODO_LIST
SET LIST_COMPLETE = 1
WHERE LIST_NO = 1;
UPDATE TODO_LIST
SET LIST_COMPLETE = 1
WHERE LIST_NO = 2;
UPDATE TODO_LIST
SET LIST_COMPLETE = 1
WHERE LIST_NO = 3;
COMMIT;

DELETE FROM TODO_LIST
WHERE LIST_NO > 17;
